idf_component_register(SRCS "main.cc"
                            "board/board.cc"
                            "common/settings.cc"
                            "common/system_info.cc"
                            "board/wifi_board.cc"
                            "board/my_wifi_pcb_board.cc"
                            "App.cc"
                            "ota.cc"
                            "device_mqtt.cc"
                            "display/display.cc"
                            "display/lvgl/cbin_font.c"
                            "display/lvgl/lvgl_font.cc"
                    INCLUDE_DIRS    "."
                                    "board/include"
                                    "common/include"
                                    "display"
                                    "display/lvgl"
                                    )
